language: node_js
node_js:
  - "stable"
scripts:
  - "npm run build"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $githubToken
  local_dir: dist
  on:
    all_branches: true
    branch: master
after_deploy:
- "echo 'deployed!'"