language: node_js
node_js:
  - "stable"
branches:
  only:
    - dev
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run lint; fi'
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: dev
