language: node_js
node_js:
  - "stable"
branches:
  only:
    - dev
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/deploy.sh; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run lint; fi'
