language: node_js
node_js:
  - "stable"
script:
  - "npm run build"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $githubToken
  local_dir: dist
  on:
    branch: dev
    target-branch: master
after_deploy:
- "echo 'deployed!'"