env:
  global:
    - GITHUB_REPO: "user/repo"
language: node_js
node_js:
  - "stable"
script:
  - "npm run build"
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: dev
after_deploy:
- "echo 'deployed!'"