export const GET_PROFILE = 'GET_PROFILE';
export const ENABLE_SEARCH_MODE = 'ENABLE_SEARCH_MODE';
export const DISABLE_SEARCH_MODE = 'DISABLE_SEARCH_MODE';
export const OPEN_MENU = 'OPEN_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';
export const GET_BLOGGER_POSTS = 'GET_BLOGGER_POSTS';
export const GET_BLOGGER_PROFILE = 'GET_BLOGGER_PROFILE';
